[package]
name = "day1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day1_a"
path = "src/a.rs"

[[bin]]
name = "day1_b"
path = "src/b.rs"

[dependencies]
