[package]
name = "day3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day3_a"
path = "src/a.rs"

[[bin]]
name = "day3_b"
path = "src/b.rs"

[dependencies]
